# Generated by Django 4.1.7 on 2023-03-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
