# Generated by Django 4.1.7 on 2023-03-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
