# Generated by Django 4.1.7 on 2023-04-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0008_article_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='titre',
        ),
    ]
