# Generated by Django 4.1.7 on 2023-04-14 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0011_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='aime',
        ),
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='akue.article'),
        ),
    ]
