# Generated by Django 4.1.7 on 2023-04-14 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0012_rename_utilisateur_like_user_remove_like_aime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='utilisateur',
        ),
        migrations.AddField(
            model_name='like',
            name='aime',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akue.article'),
        ),
    ]
