# Generated by Django 4.1.7 on 2023-04-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0013_rename_user_like_utilisateur_like_aime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
