# Generated by Django 4.1.7 on 2023-04-14 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0017_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
