# Generated by Django 4.1.7 on 2023-04-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0021_commentaireservice_alter_service_image_likeservice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like_commentaireservice',
            old_name='commentaireService',
            new_name='commentaireservice',
        ),
    ]
