# Generated by Django 4.1.7 on 2023-04-16 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0022_rename_commentaireservice_like_commentaireservice_commentaireservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaireservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentairesservice', to='akue.service'),
        ),
    ]
