# Generated by Django 4.1.7 on 2023-04-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0025_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='akue/static/akue/img/photo_de_profile/'),
        ),
    ]
