# Generated by Django 4.1.7 on 2023-04-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0026_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='static/akue/img/photo_de_profile/ma_photo.jpeg', null=True, upload_to='akue/static/akue/img/photo_de_profile/'),
        ),
    ]
