# Generated by Django 4.1.7 on 2023-04-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0027_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='akue/static/akue/img/photo_de_profile/'),
        ),
    ]
