# Generated by Django 4.1.7 on 2023-04-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0028_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
