# Generated by Django 4.1.7 on 2023-04-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0030_commentairepublication_publication_likepublication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adresse',
            field=models.CharField(default='adresse par défaut', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='metier',
            field=models.CharField(default='métier par défaut', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(default='1234567890', max_length=20),
        ),
    ]
