# Generated by Django 4.1.7 on 2023-05-17 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akue', '0032_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_publication',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
